#!/bin/bash

function _CompValArg(){

if [ $1 == 1 ]; then

	if [ "$2" != "--psuser" ]; then
		echo "Error, pruebe con --psuser"
		exit
	fi
fi

if [ $1 == 2 ]; then 
	if [ "$2" != "--countdir" ]; then
 		echo "Error, pruebe con --countdir <dir>"
		exit
	fi
fi
 
}


#Desarrollo

_CompValArg $# $1
	
if [ $# == 1 ]; then
	top -bn 1 > temporal
	numero_lineas=`cat temporal | wc -l`
	lineas_validas=$[ $numero_lineas - 8 ]
	cat temporal | tail -n $lineas_validas | sort -k 10 > archivo
	cat archivo | tail -n 10 | cut -d " " -f1,9,10,11
fi

if [ $# == 2 ]; then

if ! test -d $3 || ! test -r $3; then
	echo "Error, $3 no es un directorio o no tenemos permisos de lectura"
	exit
fi


numarch=`find $3 -type f | wc -l`
numarchr=`find $3 -type f | test -r $3 | wc -l`

echo "$3 tiene $numarch archivos totales"

echo "$3 tiene $numarchr archivos con permisos de lectura"

fi



