/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
sumar_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;
	
	result = arg1 + arg2;

	return &result;
}

int *
restar_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1 - arg2;

	return &result;
}

int *
dividir_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	if(arg2 == 0){
		printf("Control de errores: división por 0");
		result = 0;
	}
	else{
		result = arg1/arg2;
	}	

	return &result;
}

int *
multiplicar_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1 * arg2;

	return &result;
}
