/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vectores.h"


void
vectores_prog_1(char *host, miVector var1, char oper, miVector var2)
{
	CLIENT *clnt;
	miVector  *result;
	char *operacion;

#ifndef	DEBUG
	clnt = clnt_create (host, VECTORES_PROG, VECTORES_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (oper){
		case '+':
			result = sumar_1(var1, var2, clnt);
			operacion = "suma";
		break;
		case '-':
			result = restar_1(var1, var2, clnt);
			operacion = "resta";
		break;
		case '/':
			result = dividir_1(var1, var2, clnt);
			operacion = "divicion";
		break;
		case '*':
			result = multiplicar_1(var1, var2, clnt); 
			operacion = "multiplicacion";
		break;
	}

	if (result == (miVector *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("El resultado de la %s de vectores es: \n", operacion);
	printf("(%d", result->vector.vector_val[0]);
	for(int i = 1; i < result->vector.vector_len; i++){
		printf(", %d", result->vector.vector_val[i]);
	}
	printf(")\n");
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char oper;
	char *host;
	int num_elem, elem, opcion;
	miVector var1, var2;
	printf("Operaciones básicas con vectores\n");
	printf("Introduce el número de elementos de los vectores: ");
	scanf("%d",&num_elem);

	var1.vector.vector_len = num_elem;
	var1.vector.vector_val = (int*)malloc(num_elem * sizeof(int));
	var2.vector.vector_len = num_elem;
	var2.vector.vector_val = (int*)malloc(num_elem * sizeof(int));
	
	printf("Introduzca los elementos del primer vector: \n");
	for(int i = 0; i < num_elem; i++){
		printf("Elemento %d para v1: ", i);
		scanf("%d",&elem);
		var1.vector.vector_val[i] = elem;
	}

	printf("Introduzca los elementos del segundo vector: \n");
	for(int i = 0; i < num_elem; i++){
		printf("Elemento %d para v2: ", i);
		scanf("%d",&elem);
		var2.vector.vector_val[i] = elem;
	}

	printf("Eliga ahora la operación que desee realizar:\n ");
	printf("1)Sumar\n 2)Restar\n 3)Dividir\n 4)Multiplicar\n");
	printf("opcion: ");
	scanf("%d",&opcion);

	switch (opcion)
	{
		case 1:
			oper = '+';
		break;
		case 2:
			oper = '-';
		break;
		case 3:
			oper = '/';
		break;
		case 4:
			oper = '*';
		break;
	}

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	vectores_prog_1 (host, var1, oper, var2);
exit (0);
}
