/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VECTORES_H_RPCGEN
#define _VECTORES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct miVector {
	struct {
		u_int vector_len;
		int *vector_val;
	} vector;
};
typedef struct miVector miVector;

struct sumar_1_argument {
	miVector arg1;
	miVector arg2;
};
typedef struct sumar_1_argument sumar_1_argument;

struct restar_1_argument {
	miVector arg1;
	miVector arg2;
};
typedef struct restar_1_argument restar_1_argument;

struct dividir_1_argument {
	miVector arg1;
	miVector arg2;
};
typedef struct dividir_1_argument dividir_1_argument;

struct multiplicar_1_argument {
	miVector arg1;
	miVector arg2;
};
typedef struct multiplicar_1_argument multiplicar_1_argument;

#define VECTORES_PROG 0x20000001
#define VECTORES_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMAR 1
extern  miVector * sumar_1(miVector , miVector , CLIENT *);
extern  miVector * sumar_1_svc(miVector , miVector , struct svc_req *);
#define RESTAR 2
extern  miVector * restar_1(miVector , miVector , CLIENT *);
extern  miVector * restar_1_svc(miVector , miVector , struct svc_req *);
#define DIVIDIR 3
extern  miVector * dividir_1(miVector , miVector , CLIENT *);
extern  miVector * dividir_1_svc(miVector , miVector , struct svc_req *);
#define MULTIPLICAR 4
extern  miVector * multiplicar_1(miVector , miVector , CLIENT *);
extern  miVector * multiplicar_1_svc(miVector , miVector , struct svc_req *);
extern int vectores_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMAR 1
extern  miVector * sumar_1();
extern  miVector * sumar_1_svc();
#define RESTAR 2
extern  miVector * restar_1();
extern  miVector * restar_1_svc();
#define DIVIDIR 3
extern  miVector * dividir_1();
extern  miVector * dividir_1_svc();
#define MULTIPLICAR 4
extern  miVector * multiplicar_1();
extern  miVector * multiplicar_1_svc();
extern int vectores_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_miVector (XDR *, miVector*);
extern  bool_t xdr_sumar_1_argument (XDR *, sumar_1_argument*);
extern  bool_t xdr_restar_1_argument (XDR *, restar_1_argument*);
extern  bool_t xdr_dividir_1_argument (XDR *, dividir_1_argument*);
extern  bool_t xdr_multiplicar_1_argument (XDR *, multiplicar_1_argument*);

#else /* K&R C */
extern bool_t xdr_miVector ();
extern bool_t xdr_sumar_1_argument ();
extern bool_t xdr_restar_1_argument ();
extern bool_t xdr_dividir_1_argument ();
extern bool_t xdr_multiplicar_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VECTORES_H_RPCGEN */
