/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vectores.h"

bool_t
xdr_miVector (XDR *xdrs, miVector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vector.vector_val, (u_int *) &objp->vector.vector_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumar_1_argument (XDR *xdrs, sumar_1_argument *objp)
{
	 if (!xdr_miVector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_miVector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restar_1_argument (XDR *xdrs, restar_1_argument *objp)
{
	 if (!xdr_miVector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_miVector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dividir_1_argument (XDR *xdrs, dividir_1_argument *objp)
{
	 if (!xdr_miVector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_miVector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicar_1_argument (XDR *xdrs, multiplicar_1_argument *objp)
{
	 if (!xdr_miVector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_miVector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
