/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vectores.h"

miVector *
sumar_1_svc(miVector arg1, miVector arg2,  struct svc_req *rqstp)
{
	static miVector  res;
	res.vector.vector_len = arg1.vector.vector_len;
	res.vector.vector_val = (int*)malloc(arg1.vector.vector_len * sizeof(int));

	for(int i = 0; i < arg1.vector.vector_len; i++){
		res.vector.vector_val[i] = arg1.vector.vector_val[i] + arg2.vector.vector_val[i];
	}

	return &res;
}

miVector *
restar_1_svc(miVector arg1, miVector arg2,  struct svc_req *rqstp)
{
	static miVector  res;

	res.vector.vector_len = arg1.vector.vector_len;
	res.vector.vector_val = (int*)malloc(arg1.vector.vector_len * sizeof(int));

	for(int i = 0; i < arg1.vector.vector_len; i++){
		res.vector.vector_val[i] = arg1.vector.vector_val[i] - arg2.vector.vector_val[i];
	}
	return &res;
}

miVector *
dividir_1_svc(miVector arg1, miVector arg2,  struct svc_req *rqstp)
{
	static miVector  res;
	res.vector.vector_len = arg1.vector.vector_len;
	res.vector.vector_val = (int*)malloc(arg1.vector.vector_len * sizeof(int));

	for(int i = 0; i < arg1.vector.vector_len; i++){
		if(arg2.vector.vector_val[i] == 0){
			printf("Detectada división por 0, control de errores: \n");
			printf("El resultado de dicha división sera 0\n");
			res.vector.vector_val[i] = 0;
		}
		else{
			res.vector.vector_val[i] = arg1.vector.vector_val[i] / arg2.vector.vector_val[i];
		}
	}

	return &res;
}

miVector *
multiplicar_1_svc(miVector arg1, miVector arg2,  struct svc_req *rqstp)
{
	static miVector  res;

	res.vector.vector_len = arg1.vector.vector_len;
	res.vector.vector_val = (int*)malloc(arg1.vector.vector_len * sizeof(int));

	for(int i = 0; i < arg1.vector.vector_len; i++){
		res.vector.vector_val[i] = arg1.vector.vector_val[i] * arg2.vector.vector_val[i];
	}

	return &res;
}
