compila:
	g++ src/viajante_cercanias.cpp -o bin/viajante_cercanias
	g++ src/viajante_insercion.cpp -o bin/viajante_insercion
	g++ src/viajante_distancias.cpp -o bin/viajante_distancias
	g++ src/asignacion_tareas.cpp -o bin/asignacion_tareas
